#!/bin/bash

B=vc707

# CFG=rocket64b1

# CFG=rocket64b1_partition_test
# CFG=rocket64b1_partition_debug
CFG=rocket64b1_partition

# CFG=rocket64h1_partition
# CFG=rocket64h1_partition_debug

# vc707         Rocket.*parti.*   20
# vc707         Rocket.*gem.*     31.25
# vc707         Rocket64x1        50.0
# vc707         Rocket64[xyz].*   31.25
# vc707         Rocket.*l2w?      62.5
# vc707         Rocket.*b[7-9].*  62.5
# vc707         Rocket.*b[4-9].*  80.0
# vc707         Rocket.*          100.0
FREQ=62.5
# FREQ=80.0
# FREQ=50
# FREQ=31.25

MT=6
J=32

if [ "$1" = "flash" ]; then
    hw_server 2>&1 &
    sleep 2
    BOARD=$B CONFIG=$CFG ROCKET_FREQ_MHZ=$FREQ MAX_THREADS=$MT make flash-skip -j$J
    sleep 2
    PIDS=$(pgrep -x hw_server)
    if [ -z "$PIDS" ]; then
        echo "[INFO] No hw_server process running."
        exit 0
    fi

    echo -e "[INFO] Found hw_server PIDs: \n$PIDS"
    sleep 2
    kill $PIDS
    echo -e "[INFO] Killed"
elif [ "$1" = "reset" ]; then
    hw_server 2>&1 &
    sleep 2
    make reset
    sleep 2
    PIDS=$(pgrep -x hw_server)
    if [ -z "$PIDS" ]; then
        echo "[INFO] No hw_server process running."
        exit 0
    fi

    echo -e "[INFO] Found hw_server PIDs: \n$PIDS"
    sleep 2
    kill $PIDS
    echo -e "[INFO] Killed"
elif [ -z "$1" ]; then
    cp ${CFG}_log.bak.txt ${CFG}_log.bak.bak.txt && cp ${CFG}_log.txt ${CFG}_log.bak.txt
    BOARD=$B CONFIG=$CFG ROCKET_FREQ_MHZ=$FREQ MAX_THREADS=$MT make bitstream  -j$J 2>&1 | tee ${CFG}_log.txt 
    # BOARD=$B CONFIG=$CFG ROCKET_FREQ_MHZ=$FREQ MAX_THREADS=$MT make vivado-project -j$J 2>&1 | tee ${CFG}_log.txt
else
    cp ${CFG}_log.bak.txt ${CFG}_log.bak.bak.txt && cp ${CFG}_log.txt ${CFG}_log.bak.txt
    BOARD=$B CONFIG=$CFG ROCKET_FREQ_MHZ=$FREQ MAX_THREADS=$MT make $1 -j$J 2>&1 | tee ${CFG}_log.txt
fi
