create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_AXI_clock]]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[6]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/DebugTag_run_counter_rocket_DebugTag[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[6]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[7]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[8]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[9]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[10]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[11]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[12]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[13]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[14]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_H_DebugTag[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[6]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[7]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[8]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[9]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[10]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[11]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[12]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[13]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[14]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_data_L_DebugTag[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_last_chunk_DebugTag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/DebugTag_wrapper_in_valid_DebugTag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[6]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[7]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[8]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[9]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[10]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[11]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[12]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[13]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[14]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_H_DebugTag[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[6]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[7]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[8]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[9]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[10]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[11]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[12]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[13]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[14]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_data_L_DebugTag[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/accWrapper/acc/DebugTag_acc_in_valid_DebugTag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_FLAG_start_FLAG_DebugTag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe9]
set_property port_width 7 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_DebugTag[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_func_valid_DebugTag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[0]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[1]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[2]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[3]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[4]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[5]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[6]} {riscv_i/RocketChip/inst/rocket_system/tile_prci_domain/tile_reset_domain_tile/acc/cmd_router/DebugTag_run_counter_DebugTag[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_AXI_clock]
